name: Screengrab

on:
  workflow_dispatch:

  
jobs:
  screengrab:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 1
    steps:
      - uses: actions/checkout@v4
      
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install python libs
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python Font

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: android-actions/setup-android@v3

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - run: sudo gem install fastlane

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-audio -no-boot-anim -skin 1080x2340 -metrics-collection
          script: adb shell wm density 440 && fastlane screenshots

      - run: |
          rm fastlane/README.md fastlane/report.xml fastlane/metadata/android/screenshots.html

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update images
          create_branch: true
          branch: fastlane
